# Generated by Django 3.2.18 on 2023-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamad',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='teamad',
            name='game',
            field=models.CharField(choices=[('ANY', 'Any'), ('LOL', 'League of Legends'), ('WOW', 'World of Warcraft'), ('DA2', 'Defense of the Ancients 2'), ('DI4', 'Diablo 4'), ('POE', 'Path of Exile'), ('OW2', 'Overwatch 2'), ('SMI', 'Smite'), ('DAD', 'Dark and Darker')], default='ANY', max_length=3),
        ),
        migrations.AlterField(
            model_name='teamad',
            name='role',
            field=models.CharField(choices=[('ANY', 'Any'), ('DMG', 'Damage Dealer'), ('SUP', 'Support / Healer'), ('DEF', 'Tank / Defender')], default='ANY', max_length=3),
        ),
        migrations.AlterField(
            model_name='teamad',
            name='skill_level',
            field=models.CharField(choices=[('ANY', 'Any'), ('NEW', 'New player'), ('MID', 'Advanced player'), ('EXP', 'Expert player'), ('PRO', 'Proffesional player')], default='ANY', max_length=3),
        ),
    ]
