# Generated by Django 3.2.18 on 2023-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
