# Generated by Django 3.2.18 on 2023-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_teamad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamad',
            name='game',
            field=models.CharField(choices=[('League of Legends', 'League of Legends'), ('World of Warcraft', 'World of Warcraft'), ('Defense of the Ancients 2', 'Defense of the Ancients 2'), ('Diablo 4', 'Diablo 4'), ('Path of Exile', 'Path of Exile'), ('Overwatch 2', 'Overwatch 2'), ('Smite', 'Smite'), ('Dark and Darker', 'Dark and Darker')], default='League of Legends', max_length=25),
        ),
        migrations.AlterField(
            model_name='teamad',
            name='role',
            field=models.CharField(choices=[('Any', 'Any'), ('Damage Dealer', 'Damage Dealer'), ('Support / Healer', 'Support / Healer'), ('Tank / Defender', 'Tank / Defender')], default='Any', max_length=25),
        ),
        migrations.AlterField(
            model_name='teamad',
            name='skill_level',
            field=models.CharField(choices=[('Any', 'Any'), ('New player', 'New player'), ('Advanced player', 'Advanced player'), ('Expert player', 'Expert player'), ('Proffesional player', 'Proffesional player')], default='Any', max_length=25),
        ),
    ]
