# Generated by Django 3.2.18 on 2023-05-31 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_teamad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamad',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[!@#$%^&*-_+=]', inverse_match=True)], verbose_name='title (no special chars)'),
        ),
    ]
