# Generated by Django 3.2.18 on 2023-06-02 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_teamad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamad',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='title (no special chars)'),
        ),
    ]
